version: '3.9'

services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=prueba
      - MYSQL_DATABASE=ripley
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
  phpMyAdmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=db
    ports:
      - 8080:80
    depends_on:
      - db
  api:
    build: ../prueba-ripley-api
    environment:
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=prueba
      - DB_NAME=ripley
    ports:
      - 3000:3000
    depends_on:
      - db
  front:
    build: ../prueba-ripley-front
    ports:
      - 3001:80
    depends_on:
      - api
